package net.niebes.sudoku.examples

import net.niebes.sudoku.GeneratedPuzzles
import net.niebes.sudoku.HardPuzzles
import net.niebes.sudoku.Puzzles
import net.niebes.sudoku.replay.solvePuzzle
import java.io.File

/**
 * Finds, for every technique, a corpus puzzle and the step where the site can show it live.
 * The site regenerates the whole replay in the browser (the solver runs there too), so all this
 * records is where to jump - which keeps the library's examples generated rather than drawn,
 * and impossible to get out of sync with the solver.
 *
 * Runs as the `findTechniqueExamples` Gradle task during every site build. Selection favours the
 * earliest step across the corpora, so "see it live" lands somewhere a reader can rewind from.
 */
fun main(args: Array<String>) {
    val out = File(args.single())

    val best = LinkedHashMap<String, Pair<String, Int>>()
    (Puzzles.all + GeneratedPuzzles.all + HardPuzzles.all).forEach { puzzle ->
        solvePuzzle(puzzle.givens).steps.forEachIndexed { index, step ->
            val step1Based = index + 1
            val current = best[step.technique]
            if (current == null || step1Based < current.second) {
                best[step.technique] = puzzle.givens to step1Based
            }
        }
    }

    out.parentFile.mkdirs()
    out.writeText(buildString {
        appendLine("// Generated by ExampleFinder from the puzzle corpora - do not edit.")
        appendLine("// For each technique: a puzzle it fires on, and the step where it does.")
        appendLine("const TECHNIQUE_EXAMPLES = {")
        best.forEach { (technique, example) ->
            appendLine("  $technique: { puzzle: '${example.first}', step: ${example.second} },")
        }
        appendLine("};")
    })
    println("Found live examples for ${best.size} techniques: ${best.keys.joinToString(", ")}")
}
